# Generated by Django 4.2.21 on 2026-02-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('work_environment', 'بيئة العمل'), ('management', 'الإدارة'), ('salary', 'الراتب'), ('harassment', 'تحرش / إساءة'), ('other', 'أخرى')], max_length=50)),
                ('description', models.TextField()),
                ('extra_data', models.JSONField(blank=True, help_text='معلومات غير تعريفية مثل القسم أو الفرع', null=True)),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('rejected', 'مرفوضة')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
