# Generated by Django 4.2.21 on 2026-02-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='custom_reason',
            field=models.CharField(blank=True, help_text="يجب ملؤه إذا كان السبب 'أخرى'", max_length=255, null=True),
        ),
    ]
