# Generated by Django 4.2.21 on 2026-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_box', '0002_complaint_custom_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='extra_data',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='custom_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
